// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_halt 22
#define SYS_toggle 23
#define SYS_print_count 24
#define SYS_add     25
#define SYS_ps      26
#define SYS_send 27
#define SYS_recv 28
#define SYS_registerhandler 29
#define SYS_send_multi 30
#define SYS_recvmulti 31
#define SYS_samplecall 32
#define SYS_create_container 33
#define SYS_join_container 34
#define SYS_scheduler_call 35
#define SYS_leave_container 36
#define SYS_destroy_container 37
#define SYS_registerState 38
#define SYS_registerSysCall 39
#define SYS_getStatusSysCall 40
#define SYS_pop_args 41
#define SYS_getcid  42
